FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

RUN apt update && \
    apt install --no-install-recommends -y build-essential

COPY requirements-llmserver.txt /requirements-llmserver.txt

RUN pip install -r /requirements-llmserver.txt && pip cache purge

COPY . /app/

WORKDIR /app

ENTRYPOINT ["/app/scripts/entrypoint.sh"]