# Generated by Django 4.2.2 on 2023-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.BigIntegerField()),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_updated', models.DateTimeField(auto_now=True)),
                ('gmt_deleted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('user', models.BigIntegerField()),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active')], max_length=16)),
                ('type', models.CharField(choices=[('document', 'Document'), ('multimedia', 'Multimedia')], max_length=16)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_updated', models.DateTimeField(auto_now=True)),
                ('gmt_deleted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.BigIntegerField()),
                ('type', models.CharField(choices=[('pdf', 'Pdf'), ('word', 'Word'), ('markdown', 'Markdown')], max_length=16)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('FAILED', 'Failed')], max_length=16)),
                ('size', models.BigIntegerField()),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_deleted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
