# Generated by Django 4.2.4 on 2023-08-17 14:07

from django.db import migrations, models
import django.db.models.deletion
import kubechat.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DELETED", "Deleted")],
                        max_length=16,
                    ),
                ),
                ("config", models.TextField()),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                ("user", models.CharField(max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INACTIVE", "Inactive"),
                            ("ACTIVE", "Active"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("database", "Database"),
                            ("code", "Code"),
                        ],
                        max_length=16,
                    ),
                ),
                ("config", models.TextField()),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=512)),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("user", models.CharField(max_length=256)),
                ("config", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("size", models.BigIntegerField()),
                (
                    "file",
                    models.FileField(upload_to=kubechat.models.user_document_path),
                ),
                ("relate_ids", models.TextField()),
                ("metadata", models.TextField()),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kubechat.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionSyncHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                ("total_documents", models.PositiveIntegerField()),
                ("new_documents", models.PositiveIntegerField(default=0)),
                ("deleted_documents", models.PositiveIntegerField(default=0)),
                ("modified_documents", models.PositiveIntegerField(default=0)),
                ("processing_documents", models.PositiveIntegerField(default=0)),
                ("failed_documents", models.PositiveIntegerField(default=0)),
                ("successful_documents", models.PositiveIntegerField(default=0)),
                ("total_documents_to_sync", models.PositiveIntegerField(default=0)),
                ("execution_time", models.DurationField(null=True)),
                ("start_time", models.DateTimeField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kubechat.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DELETED", "Deleted")],
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField()),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kubechat.bot"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bot",
            name="collections",
            field=models.ManyToManyField(to="kubechat.collection"),
        ),
    ]
