# Generated by Django 4.2.2 on 2023-07-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="type",
            field=models.CharField(
                choices=[("document", "Document"), ("database", "Database")],
                max_length=16,
            ),
        ),
    ]
