# Generated by Django 4.2.2 on 2023-07-01 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="metadata",
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
