# Generated by Django 4.2.4 on 2023-08-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="peer_id",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="peer_type",
            field=models.CharField(
                choices=[("system", "System"), ("feishu", "Feishu")],
                default="system",
                max_length=16,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("peer_type", "peer_id")},
        ),
    ]
