# Generated by Django 4.2.5 on 2023-09-26 08:08

from django.db import migrations, models
import kubechat.models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0002_alter_bot_id_alter_chat_id_alter_collection_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionsynchistory",
            name="pending_documents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collectionsynchistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Running"),
                    ("CANCELED", "Canceled"),
                    ("COMPLETED", "Completed"),
                ],
                default="RUNNING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="collectionsynchistory",
            name="task_context",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="bot",
            name="id",
            field=models.CharField(
                default=kubechat.models.bot_pk,
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.CharField(
                default=kubechat.models.chat_pk,
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.CharField(
                default=kubechat.models.collection_pk,
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="collectionsynchistory",
            name="id",
            field=models.CharField(
                default=kubechat.models.collection_history_pk,
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="collectionsynchistory",
            name="total_documents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.CharField(
                default=kubechat.models.doc_pk,
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
