# Generated by Django 4.2.3 on 2023-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0002_alter_document_relate_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="metadata",
            field=models.TextField(),
        ),
    ]
