# Generated by Django 4.2.4 on 2023-08-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0002_chat_peer_id_chat_peer_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                ("message_id", models.CharField(max_length=256)),
                ("upvote", models.IntegerField(default=0)),
                ("downvote", models.IntegerField(default=0)),
                ("revised_answer", models.TextField(blank=True, null=True)),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kubechat.chat"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kubechat.collection",
                    ),
                ),
            ],
            options={
                "unique_together": {("chat_id", "message_id")},
            },
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.AlterField(
            model_name="document",
            name="metadata",
            field=models.TextField(default="{}"),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("collection", "name")},
        ),
    ]
