# Generated by Django 4.2.4 on 2023-08-17 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0003_alter_document_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionSyncHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                ("total_documents", models.PositiveIntegerField()),
                ("new_documents", models.PositiveIntegerField(default=0)),
                ("deleted_documents", models.PositiveIntegerField(default=0)),
                ("modified_documents", models.PositiveIntegerField(default=0)),
                ("processing_documents", models.PositiveIntegerField(default=0)),
                ("failed_documents", models.PositiveIntegerField(default=0)),
                ("successful_documents", models.PositiveIntegerField(default=0)),
                ("total_documents_to_sync", models.PositiveIntegerField(default=0)),
                ("execution_time", models.DurationField(null=True)),
                ("start_time", models.DateTimeField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kubechat.collection",
                    ),
                ),
            ],
        ),
    ]
