# Generated by Django 4.2.4 on 2023-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0003_messagefeedback_delete_settings_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messagefeedback",
            old_name="revised_answer",
            new_name="original_answer",
        ),
        migrations.AddField(
            model_name="messagefeedback",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagefeedback",
            name="revised_answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
