# Generated by Django 4.2.4 on 2023-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "kubechat",
            "0004_rename_expect_answer_messagefeedback_origin_answer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefeedback",
            name="relate_ids",
            field=models.TextField(null=True),
        ),
    ]
