# Generated by Django 4.2.4 on 2023-08-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0005_messagefeedback_relate_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefeedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
