# Generated by Django 4.2.6 on 2023-12-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0006_document_sensitive_info_alter_botintegration_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=256)),
                ("value", models.PositiveIntegerField(default=0)),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                ("key", models.CharField(max_length=256)),
                ("value", models.PositiveIntegerField(default=0)),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="id",
            field=models.CharField(
                default="int605eefbd5ffb451f",
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
