# Generated by Django 4.2.6 on 2023-12-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubechat', '0007_quota_userquota_collectionsynchistory_gmt_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('bot', 'peer_type', 'peer_id')},
        ),
    ]
