# Generated by Django 4.2.6 on 2023-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0009_alter_chat_peer_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=256, unique=True)),
                ("value", models.TextField()),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Quota",
        ),
    ]
