# Generated by Django 4.2.6 on 2024-01-01 01:05

import django.db.models.deletion
from django.db import migrations, models

import kubechat.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('kubechat', '0011_bot_type_alter_botintegration_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=kubechat.db.models.que_pk, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=256)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WARNING', 'Warning'), ('DELETED', 'Deleted'), ('PENDING', 'Pending')], max_length=16, null=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_updated', models.DateTimeField(auto_now=True)),
                ('gmt_deleted', models.DateTimeField(blank=True, null=True)),
                ('relate_id', models.CharField(max_length=256, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubechat.collection')),
                ('documents', models.ManyToManyField(blank=True, to='kubechat.document')),
            ],
        ),
    ]
