# Generated by Django 4.2.6 on 2024-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0012_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="need_generate",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
