# Generated by Django 4.2.6 on 2024-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubechat', '0012_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='question_status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('PENDING', 'Pending')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('PENDING', 'Pending')], max_length=16),
        ),
    ]
