# Generated by Django 4.2.6 on 2024-01-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kubechat", "0012_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagefeedback",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kubechat.collection",
            ),
        ),
    ]
