# Generated by Django 4.2.9 on 2024-03-05 14:50

from django.db import migrations, models
import kubechat.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('kubechat', '0014_merge_20240111_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyToken',
            fields=[
                ('id', models.CharField(default=kubechat.db.models.app_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('key', models.CharField(default=kubechat.db.models.app_key, editable=False, max_length=40)),
                ('user', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], max_length=16, null=True)),
                ('count_times', models.IntegerField(blank=True, null=True)),
                ('gmt_updated', models.DateTimeField(auto_now=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
