# Generated by Django 4.2.5 on 2023-09-25 09:43

from django.db import migrations, models

import aperag.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("aperag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="id",
            field=models.CharField(
                default=aperag.db.models.bot_pk,
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.CharField(
                default=aperag.db.models.chat_pk,
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.CharField(
                default=aperag.db.models.collection_pk,
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="collectionsynchistory",
            name="id",
            field=models.CharField(
                default=aperag.db.models.collection_history_pk,
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=1024, upload_to=aperag.db.models.upload_document_path
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.CharField(
                default=aperag.db.models.doc_pk,
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
