# Generated by Django 5.0.14 on 2025-04-27 09:13

import aperag.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=aperag.db.models.ApiKey.generate_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=aperag.db.models.ApiKey.generate_key,
                        editable=False,
                        max_length=40,
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DELETED", "Deleted")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ApiKeyToken",
        ),
    ]
