# Copyright 2025 ApeCloud, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.14 on 2025-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Unique provider name identifier",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable provider display name", max_length=256
                    ),
                ),
                (
                    "completion_dialect",
                    models.CharField(
                        help_text="API dialect for completion/chat APIs", max_length=64
                    ),
                ),
                (
                    "embedding_dialect",
                    models.CharField(
                        help_text="API dialect for embedding APIs", max_length=64
                    ),
                ),
                (
                    "rerank_dialect",
                    models.CharField(
                        help_text="API dialect for rerank APIs", max_length=64
                    ),
                ),
                (
                    "allow_custom_base_url",
                    models.BooleanField(
                        default=False, help_text="Whether custom base URLs are allowed"
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Default API base URL for this provider",
                        max_length=512,
                    ),
                ),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "aperag_llm_provider",
            },
        ),
        migrations.CreateModel(
            name="LLMProviderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        help_text="Reference to LLMProvider.name", max_length=128
                    ),
                ),
                (
                    "api",
                    models.CharField(
                        choices=[
                            ("completion", "Completion"),
                            ("embedding", "Embedding"),
                            ("rerank", "Rerank"),
                        ],
                        help_text="API type for this model",
                        max_length=16,
                    ),
                ),
                (
                    "model",
                    models.CharField(help_text="Model name/identifier", max_length=256),
                ),
                (
                    "custom_llm_provider",
                    models.CharField(
                        help_text="Custom LLM provider implementation", max_length=128
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum tokens for this model", null=True
                    ),
                ),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "aperag_llm_provider_models",
                "indexes": [
                    models.Index(
                        fields=["provider_name"], name="aperag_llm__provide_9a9bdc_idx"
                    ),
                    models.Index(fields=["api"], name="aperag_llm__api_91e21d_idx"),
                    models.Index(
                        fields=["provider_name", "api"],
                        name="aperag_llm__provide_e4753c_idx",
                    ),
                ],
                "unique_together": {("provider_name", "api", "model")},
            },
        ),
    ]
