# Generated by Django 5.0.14 on 2025-04-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0002_apikey_delete_apikeytoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelserviceprovider",
            name="dialect",
            field=models.CharField(default="openai", max_length=32),
        ),
    ]
