# Copyright 2025 ApeCloud, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.14 on 2025-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0003_modelserviceprovider_dialect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagefeedback",
            name="downvote",
        ),
        migrations.RemoveField(
            model_name="messagefeedback",
            name="upvote",
        ),
        migrations.AddField(
            model_name="messagefeedback",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagefeedback",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Harmful", "Harmful"),
                    ("Unsafe", "Unsafe"),
                    ("Fake", "Fake"),
                    ("Unhelpful", "Unhelpful"),
                    ("Other", "Other"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="messagefeedback",
            name="type",
            field=models.CharField(
                choices=[("good", "Good"), ("bad", "Bad")], max_length=16, null=True
            ),
        ),
    ]
