# Copyright 2025 ApeCloud, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.14 on 2025-06-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0003_add_tags_field_to_llm_provider_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelserviceprovider",
            name="base_url",
        ),
        migrations.RemoveField(
            model_name="modelserviceprovider",
            name="completion_dialect",
        ),
        migrations.RemoveField(
            model_name="modelserviceprovider",
            name="embedding_dialect",
        ),
        migrations.RemoveField(
            model_name="modelserviceprovider",
            name="extra",
        ),
        migrations.RemoveField(
            model_name="modelserviceprovider",
            name="rerank_dialect",
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="extra",
            field=models.TextField(
                help_text="Additional configuration data in JSON format", null=True
            ),
        ),
    ]
