# Generated by Django 5.0.14 on 2025-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0003_modelserviceprovider_dialect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagefeedback",
            name="downvote",
        ),
        migrations.RemoveField(
            model_name="messagefeedback",
            name="upvote",
        ),
        migrations.AddField(
            model_name="messagefeedback",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagefeedback",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Harmful", "Harmful"),
                    ("Unsafe", "Unsafe"),
                    ("Fake", "Fake"),
                    ("Unhelpful", "Unhelpful"),
                    ("Other", "Other"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="messagefeedback",
            name="type",
            field=models.CharField(
                choices=[("good", "Good"), ("bad", "Bad")], max_length=16, null=True
            ),
        ),
    ]
