# Generated by Django 4.2.6 on 2023-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aperag", "0003_collectionsynchistory_pending_documents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                    ("DELETING", "Deleting"),
                    ("DELETED", "Deleted"),
                ],
                max_length=16,
            ),
        ),
    ]
