# Copyright 2025 ApeCloud, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.14 on 2025-05-09 07:42

import aperag.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0004_remove_messagefeedback_downvote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTestHistory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=aperag.db.models.SearchTestHistory.generate_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                ("collection_id", models.CharField(max_length=24, null=True)),
                ("query", models.TextField()),
                ("search_type", models.CharField(max_length=16)),
                ("vector_search", models.JSONField(blank=True, null=True)),
                ("fulltext_search", models.JSONField(blank=True, null=True)),
                ("items", models.JSONField(default=list)),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
