# Generated by Django 5.0.14 on 2025-05-09 07:42

import aperag.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0004_remove_messagefeedback_downvote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTestHistory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=aperag.db.models.SearchTestHistory.generate_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                ("collection_id", models.CharField(max_length=24, null=True)),
                ("query", models.TextField()),
                ("search_type", models.CharField(max_length=16)),
                ("vector_search", models.JSONField(blank=True, null=True)),
                ("fulltext_search", models.JSONField(blank=True, null=True)),
                ("items", models.JSONField(default=list)),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
