# Copyright 2025 ApeCloud, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.14 on 2025-05-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0005_searchtesthistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AddField(
            model_name="document",
            name="object_path",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
