# Generated by Django 4.2.6 on 2023-11-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aperag", "0005_alter_chat_peer_type_botintegration"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="sensitive_info",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="id",
            field=models.CharField(
                default="int66670fff0ab05826",
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                    ("DELETING", "Deleting"),
                    ("DELETED", "Deleted"),
                    ("WARNING", "Warning"),
                ],
                max_length=16,
            ),
        ),
    ]
