# Generated by Django 5.0.14 on 2025-05-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0005_searchtesthistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AddField(
            model_name="document",
            name="object_path",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
