# Generated by Django 5.0.14 on 2025-05-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0006_remove_document_file_document_object_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="fulltext_index_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="graph_index_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="vector_index_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
