# Generated by Django 5.0.14 on 2025-05-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0007_document_fulltext_index_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="sensitive_info",
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                    ("DELETING", "Deleting"),
                    ("DELETED", "Deleted"),
                ],
                max_length=16,
            ),
        ),
    ]
