# Copyright 2025 ApeCloud, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.14 on 2025-05-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0007_document_fulltext_index_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="sensitive_info",
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                    ("DELETING", "Deleting"),
                    ("DELETED", "Deleted"),
                ],
                max_length=16,
            ),
        ),
    ]
