# Generated by Django 5.0.14 on 2025-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0008_remove_document_sensitive_info_alter_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtesthistory",
            name="graph_search",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
