# Generated by Django 5.0.14 on 2025-05-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0009_searchtesthistory_graph_search"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchtesthistory",
            name="search_type",
        ),
    ]
