# Generated by Django 4.2.6 on 2023-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aperag", "0010_config_delete_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="type",
            field=models.CharField(
                choices=[("knowledge", "Knowledge"), ("common", "Common")],
                default="knowledge",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("feishu", "Feishu"),
                    ("web", "Web"),
                    ("weixin", "Weixn"),
                    ("weixin_official", "Weixin Official"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="peer_type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("feishu", "Feishu"),
                    ("weixin", "Weixin"),
                    ("weixin_official", "Weixin Official"),
                    ("web", "Web"),
                    ("dingtalk", "Dingtalk"),
                ],
                default="system",
                max_length=16,
            ),
        ),
    ]
