# Generated by Django 4.2.6 on 2024-01-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aperag', '0013_alter_collection_status'),
        ('aperag', '0013_alter_messagefeedback_collection'),
    ]

    operations = [
    ]
