# Generated by Django 4.2.6 on 2024-03-07 02:17

from django.db import migrations, models
import aperag.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("aperag", "0014_merge_20240111_0214"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKeyToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=aperag.db.models.app_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(editable=False, max_length=40)),
                ("user", models.CharField(max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DELETED", "Deleted")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("count_times", models.IntegerField(blank=True, null=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
