# Generated by Django 4.2.20 on 2025-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperag', '0016_default_api_key_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsynchistory',
            name='task_context',
            field=models.JSONField(default=dict),
        ),
    ]
