# Generated by Django 4.2.20 on 2025-04-22 01:03

import aperag.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperag', '0017_alter_collectionsynchistory_task_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelServiceProvider',
            fields=[
                ('name', models.CharField(default=aperag.db.models.ModelServiceProvider.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], max_length=16)),
                ('base_url', models.CharField(blank=True, max_length=256, null=True)),
                ('api_key', models.CharField(max_length=256)),
                ('extra', models.TextField(null=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_updated', models.DateTimeField(auto_now=True)),
                ('gmt_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
