# Generated by Django 5.0.14 on 2025-04-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0018_user_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("rw", "Rw"), ("ro", "Ro")],
                default="ro",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("rw", "Rw"), ("ro", "Ro")],
                default="ro",
                max_length=16,
            ),
        ),
    ]
