# Generated by Django 5.0.14 on 2025-04-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0019_invitation_role_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="created_by",
            field=models.CharField(max_length=256),
        ),
    ]
