# Generated by Django 5.0.14 on 2025-04-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0019_invitation_rename_summary_chat_title_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BotIntegration",
        ),
    ]
