# Generated by Django 5.0.14 on 2025-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0020_alter_invitation_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="type",
            field=models.CharField(choices=[("document", "Document")], max_length=16),
        ),
    ]
