# Generated by Django 5.0.14 on 2025-04-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aperag", "0021_alter_collection_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="summary",
            new_name="title",
        ),
    ]
