/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Chat } from './chat';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * A list of chats
 * @export
 * @interface ChatList
 */
export interface ChatList {
    /**
     * 
     * @type {Array<Chat>}
     * @memberof ChatList
     */
    'items'?: Array<Chat>;
    /**
     * 
     * @type {PageResult}
     * @memberof ChatList
     */
    'pageResult'?: PageResult;
}

