/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionsCollectionIdSyncPost200ResponseStats } from './collections-collection-id-sync-post200-response-stats';

/**
 * 
 * @export
 * @interface CollectionsCollectionIdSyncPost200Response
 */
export interface CollectionsCollectionIdSyncPost200Response {
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionIdSyncPost200Response
     */
    'collection_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionIdSyncPost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionIdSyncPost200Response
     */
    'status'?: string;
    /**
     * 
     * @type {CollectionsCollectionIdSyncPost200ResponseStats}
     * @memberof CollectionsCollectionIdSyncPost200Response
     */
    'stats'?: CollectionsCollectionIdSyncPost200ResponseStats;
}

