/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Anybase object storage source configuration. Endpoint, access_key, secret_key, bucket, and enable_path_style are configured via environment variables.
 * @export
 * @interface CollectionConfigAnybase
 */
export interface CollectionConfigAnybase {
    /**
     * Prefix for object keys to be included in the collection. Only objects with keys matching this prefix will be considered.
     * @type {string}
     * @memberof CollectionConfigAnybase
     */
    'object_prefix'?: string;
    /**
     * Whitelist of complete object keys. Only objects with keys in this list will be included in the collection.
     * @type {Array<string>}
     * @memberof CollectionConfigAnybase
     */
    'include_filters'?: Array<string>;
    /**
     * Blacklist of complete object keys. Objects with keys in this list will be excluded from the collection. Takes precedence over include_filters if an object appears in both.
     * @type {Array<string>}
     * @memberof CollectionConfigAnybase
     */
    'exclude_filters'?: Array<string>;
}

