/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionConfigObjectStorage
 */
export interface CollectionConfigObjectStorage {
    /**
     * 
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'access_key_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'access_key_secret'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionConfigObjectStorage
     */
    'enable_path_style'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'bucket'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'region'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CollectionConfigObjectStorage
     */
    'objects'?: Array<string>;
}

