/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Object storage source configuration (S3, MinIO, etc.)
 * @export
 * @interface CollectionConfigObjectStorage
 */
export interface CollectionConfigObjectStorage {
    /**
     * Object storage endpoint URL
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'endpoint': string;
    /**
     * Access key for object storage authentication
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'access_key': string;
    /**
     * Secret key for object storage authentication
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'secret_key': string;
    /**
     * Whether to use path-style URLs for object storage. Set to false for MinIO.
     * @type {boolean}
     * @memberof CollectionConfigObjectStorage
     */
    'enable_path_style'?: boolean;
    /**
     * Bucket name in object storage
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'bucket': string;
    /**
     * Object storage region
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'region'?: string;
    /**
     * Prefix for object keys to be included in the collection. Only objects with keys matching this prefix will be considered.
     * @type {string}
     * @memberof CollectionConfigObjectStorage
     */
    'object_prefix': string;
    /**
     * Whitelist of complete object keys. Only objects with keys in this list will be included in the collection.
     * @type {Array<string>}
     * @memberof CollectionConfigObjectStorage
     */
    'include_filters'?: Array<string>;
    /**
     * Blacklist of complete object keys. Objects with keys in this list will be excluded from the collection. Takes precedence over include_filters if an object appears in both.
     * @type {Array<string>}
     * @memberof CollectionConfigObjectStorage
     */
    'exclude_filters'?: Array<string>;
}

