/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionConfigObjectStorage } from './collection-config-object-storage';
// May contain unused imports in some cases
// @ts-ignore
import type { CrontabConfig } from './crontab-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelSpec } from './model-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { ParserConfig } from './parser-config';

/**
 * 
 * @export
 * @interface CollectionConfig
 */
export interface CollectionConfig {
    /**
     * Source system identifier
     * @type {string}
     * @memberof CollectionConfig
     */
    'source'?: string;
    /**
     * 
     * @type {CrontabConfig}
     * @memberof CollectionConfig
     */
    'crontab'?: CrontabConfig;
    /**
     * Whether to enable knowledge graph
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_knowledge_graph'?: boolean;
    /**
     * Whether to enable summary generation
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_summary'?: boolean;
    /**
     * Whether to enable vision index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_vision'?: boolean;
    /**
     * Embedding model configuration for vector indexing. Use /api/v1/available_models to get available models.
     * @type {ModelSpec}
     * @memberof CollectionConfig
     */
    'embedding'?: ModelSpec;
    /**
     * Completion model configuration for text generation. Use /api/v1/available_models to get available models.
     * @type {ModelSpec}
     * @memberof CollectionConfig
     */
    'completion'?: ModelSpec;
    /**
     * 
     * @type {ParserConfig}
     * @memberof CollectionConfig
     */
    'parser'?: ParserConfig;
    /**
     * 
     * @type {object}
     * @memberof CollectionConfig
     */
    'system'?: object;
    /**
     * 
     * @type {CollectionConfigObjectStorage}
     * @memberof CollectionConfig
     */
    'object_storage'?: CollectionConfigObjectStorage;
}

