/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Collection } from './collection';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * A list of collections
 * @export
 * @interface CollectionList
 */
export interface CollectionList {
    /**
     * 
     * @type {Array<Collection>}
     * @memberof CollectionList
     */
    'items'?: Array<Collection>;
    /**
     * 
     * @type {PageResult}
     * @memberof CollectionList
     */
    'pageResult'?: PageResult;
}

