/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionsCollectionIdSyncPost200ResponseStats
 */
export interface CollectionsCollectionIdSyncPost200ResponseStats {
    /**
     * 
     * @type {number}
     * @memberof CollectionsCollectionIdSyncPost200ResponseStats
     */
    'total_objects'?: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionsCollectionIdSyncPost200ResponseStats
     */
    'new_documents'?: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionsCollectionIdSyncPost200ResponseStats
     */
    'updated_documents'?: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionsCollectionIdSyncPost200ResponseStats
     */
    'deleted_documents'?: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionsCollectionIdSyncPost200ResponseStats
     */
    'failed_documents'?: number;
}

