/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Document
 */
export interface Document {
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'status'?: DocumentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'vector_index_status'?: DocumentVectorIndexStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'fulltext_index_status'?: DocumentFulltextIndexStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'graph_index_status'?: DocumentGraphIndexStatusEnum;
    /**
     * Vector index last updated time
     * @type {string}
     * @memberof Document
     */
    'vector_index_updated'?: string;
    /**
     * Fulltext index last updated time
     * @type {string}
     * @memberof Document
     */
    'fulltext_index_updated'?: string;
    /**
     * Graph index last updated time
     * @type {string}
     * @memberof Document
     */
    'graph_index_updated'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'config'?: string;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'updated'?: string;
}

export const DocumentStatusEnum = {
    PENDING: 'PENDING',
    RUNNING: 'RUNNING',
    COMPLETE: 'COMPLETE',
    FAILED: 'FAILED',
    DELETING: 'DELETING',
    DELETED: 'DELETED',
    WARNING: 'WARNING'
} as const;

export type DocumentStatusEnum = typeof DocumentStatusEnum[keyof typeof DocumentStatusEnum];
export const DocumentVectorIndexStatusEnum = {
    PENDING: 'PENDING',
    RUNNING: 'RUNNING',
    COMPLETE: 'COMPLETE',
    FAILED: 'FAILED',
    SKIPPED: 'SKIPPED'
} as const;

export type DocumentVectorIndexStatusEnum = typeof DocumentVectorIndexStatusEnum[keyof typeof DocumentVectorIndexStatusEnum];
export const DocumentFulltextIndexStatusEnum = {
    PENDING: 'PENDING',
    RUNNING: 'RUNNING',
    COMPLETE: 'COMPLETE',
    FAILED: 'FAILED',
    SKIPPED: 'SKIPPED'
} as const;

export type DocumentFulltextIndexStatusEnum = typeof DocumentFulltextIndexStatusEnum[keyof typeof DocumentFulltextIndexStatusEnum];
export const DocumentGraphIndexStatusEnum = {
    PENDING: 'PENDING',
    RUNNING: 'RUNNING',
    COMPLETE: 'COMPLETE',
    FAILED: 'FAILED',
    SKIPPED: 'SKIPPED'
} as const;

export type DocumentGraphIndexStatusEnum = typeof DocumentGraphIndexStatusEnum[keyof typeof DocumentGraphIndexStatusEnum];


