/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Document
 */
export interface Document {
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'status'?: DocumentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'config'?: string;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'updated'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Document
     */
    'sensitive_info'?: Array<string>;
}

export const DocumentStatusEnum = {
    PENDING: 'PENDING',
    RUNNING: 'RUNNING',
    COMPLETE: 'COMPLETE',
    FAILED: 'FAILED',
    DELETING: 'DELETING',
    DELETED: 'DELETED',
    WARNING: 'WARNING'
} as const;

export type DocumentStatusEnum = typeof DocumentStatusEnum[keyof typeof DocumentStatusEnum];


