/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Edge
 */
export interface Edge {
    /**
     * ID of the source node
     * @type {string}
     * @memberof Edge
     */
    'source': string;
    /**
     * ID of the target node
     * @type {string}
     * @memberof Edge
     */
    'target': string;
}

