/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const EdgeType = {
    straight: 'straight',
    step: 'step',
    smoothstep: 'smoothstep',
    default: 'default',
    simplebezier: 'simplebezier'
} as const;

export type EdgeType = typeof EdgeType[keyof typeof EdgeType];



