/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Feedback
 */
export interface Feedback {
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    'upvote'?: number;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    'downvote'?: number;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    'revised_answer'?: string;
}

