/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LlmProviderUpdate
 */
export interface LlmProviderUpdate {
    /**
     * Human-readable provider display name
     * @type {string}
     * @memberof LlmProviderUpdate
     */
    'label'?: string;
    /**
     * API dialect for completion/chat APIs
     * @type {string}
     * @memberof LlmProviderUpdate
     */
    'completion_dialect'?: string;
    /**
     * API dialect for embedding APIs
     * @type {string}
     * @memberof LlmProviderUpdate
     */
    'embedding_dialect'?: string;
    /**
     * API dialect for rerank APIs
     * @type {string}
     * @memberof LlmProviderUpdate
     */
    'rerank_dialect'?: string;
    /**
     * Whether custom base URLs are allowed
     * @type {boolean}
     * @memberof LlmProviderUpdate
     */
    'allow_custom_base_url'?: boolean;
    /**
     * Default API base URL for this provider
     * @type {string}
     * @memberof LlmProviderUpdate
     */
    'base_url'?: string;
    /**
     * Additional configuration data in JSON format
     * @type {string}
     * @memberof LlmProviderUpdate
     */
    'extra'?: string;
}

