/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MergeSuggestionEntity } from './merge-suggestion-entity';
// May contain unused imports in some cases
// @ts-ignore
import type { MergeSuggestionTargetEntity } from './merge-suggestion-target-entity';

/**
 * Node merge suggestion
 * @export
 * @interface MergeSuggestion
 */
export interface MergeSuggestion {
    /**
     * List of entities suggested for merging
     * @type {Array<MergeSuggestionEntity>}
     * @memberof MergeSuggestion
     */
    'entities': Array<MergeSuggestionEntity>;
    /**
     * LLM confidence score for this merge suggestion
     * @type {number}
     * @memberof MergeSuggestion
     */
    'confidence_score': number;
    /**
     * LLM-generated reason for suggesting this merge
     * @type {string}
     * @memberof MergeSuggestion
     */
    'merge_reason': string;
    /**
     * 
     * @type {MergeSuggestionTargetEntity}
     * @memberof MergeSuggestion
     */
    'suggested_target_entity': MergeSuggestionTargetEntity;
}

