/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request for generating node merge suggestions
 * @export
 * @interface MergeSuggestionsRequest
 */
export interface MergeSuggestionsRequest {
    /**
     * Maximum number of merge suggestions to return
     * @type {number}
     * @memberof MergeSuggestionsRequest
     */
    'max_suggestions'?: number;
    /**
     * Only consider entities of specified types (empty means all types)
     * @type {Array<string>}
     * @memberof MergeSuggestionsRequest
     */
    'entity_types'?: Array<string>;
    /**
     * Enable debug mode with lower confidence threshold (0.3 vs 0.6) and verbose logging
     * @type {boolean}
     * @memberof MergeSuggestionsRequest
     */
    'debug_mode'?: boolean;
    /**
     * Maximum number of concurrent LLM calls for batch analysis
     * @type {number}
     * @memberof MergeSuggestionsRequest
     */
    'max_concurrent_llm_calls'?: number;
}

