/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelSpec
 */
export interface ModelSpec {
    /**
     * 
     * @type {string}
     * @memberof ModelSpec
     */
    'model'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSpec
     */
    'custom_llm_provider'?: string;
}

