/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelServiceProviderUpdate
 */
export interface ModelServiceProviderUpdate {
    /**
     * 
     * @type {string}
     * @memberof ModelServiceProviderUpdate
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelServiceProviderUpdate
     */
    'api_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelServiceProviderUpdate
     */
    'base_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelServiceProviderUpdate
     */
    'extra'?: string;
}

