/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Model } from './model';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * A list of models
 * @export
 * @interface ModelList
 */
export interface ModelList {
    /**
     * 
     * @type {Array<Model>}
     * @memberof ModelList
     */
    'items'?: Array<Model>;
    /**
     * 
     * @type {PageResult}
     * @memberof ModelList
     */
    'pageResult'?: PageResult;
}

