/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeMergeResponseTargetEntityData } from './node-merge-response-target-entity-data';

/**
 * Response containing node merge results
 * @export
 * @interface NodeMergeResponse
 */
export interface NodeMergeResponse {
    /**
     * Status of the merge operation
     * @type {string}
     * @memberof NodeMergeResponse
     */
    'status': NodeMergeResponseStatusEnum;
    /**
     * Detailed message about the merge operation
     * @type {string}
     * @memberof NodeMergeResponse
     */
    'message': string;
    /**
     * 
     * @type {NodeMergeResponseTargetEntityData}
     * @memberof NodeMergeResponse
     */
    'target_entity_data': NodeMergeResponseTargetEntityData;
    /**
     * List of entities that were merged into the target
     * @type {Array<string>}
     * @memberof NodeMergeResponse
     */
    'source_entities': Array<string>;
    /**
     * Number of edges that were redirected during merge
     * @type {number}
     * @memberof NodeMergeResponse
     */
    'redirected_edges': number;
    /**
     * Length of the merged description
     * @type {number}
     * @memberof NodeMergeResponse
     */
    'merged_description_length': number;
}

export const NodeMergeResponseStatusEnum = {
    success: 'success',
    error: 'error'
} as const;

export type NodeMergeResponseStatusEnum = typeof NodeMergeResponseStatusEnum[keyof typeof NodeMergeResponseStatusEnum];


