/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeData } from './node-data';

/**
 * 
 * @export
 * @interface Node
 */
export interface Node {
    /**
     * Unique identifier for the node
     * @type {string}
     * @memberof Node
     */
    'id': string;
    /**
     * Type of node
     * @type {string}
     * @memberof Node
     */
    'type': string;
    /**
     * Human-readable title of the node
     * @type {string}
     * @memberof Node
     */
    'title': string;
    /**
     * 
     * @type {NodeData}
     * @memberof Node
     */
    'data': NodeData;
}

