/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';
// May contain unused imports in some cases
// @ts-ignore
import type { Question } from './question';

/**
 * A list of questions
 * @export
 * @interface QuestionList
 */
export interface QuestionList {
    /**
     * 
     * @type {Array<Question>}
     * @memberof QuestionList
     */
    'items'?: Array<Question>;
    /**
     * 
     * @type {PageResult}
     * @memberof QuestionList
     */
    'pageResult'?: PageResult;
}

