/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';
// May contain unused imports in some cases
// @ts-ignore
import type { SupportedModelServiceProvider } from './supported-model-service-provider';

/**
 * 
 * @export
 * @interface SupportedModelServiceProviderList
 */
export interface SupportedModelServiceProviderList {
    /**
     * 
     * @type {Array<SupportedModelServiceProvider>}
     * @memberof SupportedModelServiceProviderList
     */
    'items'?: Array<SupportedModelServiceProvider>;
    /**
     * 
     * @type {PageResult}
     * @memberof SupportedModelServiceProviderList
     */
    'pageResult'?: PageResult;
}

