/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WebReadRequestUrls } from './web-read-request-urls';

/**
 * Web content reading request
 * @export
 * @interface WebReadRequest
 */
export interface WebReadRequest {
    /**
     * 
     * @type {WebReadRequestUrls}
     * @memberof WebReadRequest
     */
    'urls': WebReadRequestUrls;
    /**
     * Request timeout in seconds
     * @type {number}
     * @memberof WebReadRequest
     */
    'timeout'?: number;
    /**
     * Browser locale
     * @type {string}
     * @memberof WebReadRequest
     */
    'locale'?: string;
    /**
     * Maximum concurrent requests for multiple URLs
     * @type {number}
     * @memberof WebReadRequest
     */
    'max_concurrent'?: number;
}

