"""empty message

Revision ID: f164d19a0fd9
Revises: f7146daca05c
Create Date: 2025-07-29 15:38:11.394594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f164d19a0fd9'
down_revision: Union[str, None] = 'f7146daca05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_active_merge_suggestions',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=False),
    sa.Column('suggestion_batch_id', sa.String(length=24), nullable=False),
    sa.Column('entity_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('entity_ids_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('merge_reason', sa.Text(), nullable=False),
    sa.Column('suggested_target_entity', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('graph_version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'entity_ids_hash', name='uq_active_merge_suggestion')
    )
    op.create_index('idx_active_merge_suggestion_batch', 'graph_active_merge_suggestions', ['collection_id', 'suggestion_batch_id'], unique=False)
    op.create_index('idx_active_merge_suggestion_collection', 'graph_active_merge_suggestions', ['collection_id'], unique=False)
    op.create_index('idx_active_merge_suggestion_created', 'graph_active_merge_suggestions', ['gmt_created'], unique=False)
    op.create_index(op.f('ix_graph_active_merge_suggestions_collection_id'), 'graph_active_merge_suggestions', ['collection_id'], unique=False)
    op.create_index(op.f('ix_graph_active_merge_suggestions_status'), 'graph_active_merge_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_graph_active_merge_suggestions_suggestion_batch_id'), 'graph_active_merge_suggestions', ['suggestion_batch_id'], unique=False)
    op.create_table('graph_merge_suggestion_history',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('original_suggestion_id', sa.String(length=24), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=False),
    sa.Column('suggestion_batch_id', sa.String(length=24), nullable=False),
    sa.Column('entity_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('entity_ids_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('merge_reason', sa.Text(), nullable=False),
    sa.Column('suggested_target_entity', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operated_by', sa.String(length=24), nullable=True),
    sa.Column('graph_version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_merge_suggestion_history_collection', 'graph_merge_suggestion_history', ['collection_id'], unique=False)
    op.create_index('idx_merge_suggestion_history_collection_status', 'graph_merge_suggestion_history', ['collection_id', 'status'], unique=False)
    op.create_index('idx_merge_suggestion_history_operated_at', 'graph_merge_suggestion_history', ['operated_at'], unique=False)
    op.create_index('idx_merge_suggestion_history_original_id', 'graph_merge_suggestion_history', ['original_suggestion_id'], unique=False)
    op.create_index(op.f('ix_graph_merge_suggestion_history_collection_id'), 'graph_merge_suggestion_history', ['collection_id'], unique=False)
    op.create_index(op.f('ix_graph_merge_suggestion_history_original_suggestion_id'), 'graph_merge_suggestion_history', ['original_suggestion_id'], unique=False)
    op.create_index(op.f('ix_graph_merge_suggestion_history_status'), 'graph_merge_suggestion_history', ['status'], unique=False)
    op.create_index(op.f('ix_graph_merge_suggestion_history_suggestion_batch_id'), 'graph_merge_suggestion_history', ['suggestion_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_merge_suggestion_history_suggestion_batch_id'), table_name='graph_merge_suggestion_history')
    op.drop_index(op.f('ix_graph_merge_suggestion_history_status'), table_name='graph_merge_suggestion_history')
    op.drop_index(op.f('ix_graph_merge_suggestion_history_original_suggestion_id'), table_name='graph_merge_suggestion_history')
    op.drop_index(op.f('ix_graph_merge_suggestion_history_collection_id'), table_name='graph_merge_suggestion_history')
    op.drop_index('idx_merge_suggestion_history_original_id', table_name='graph_merge_suggestion_history')
    op.drop_index('idx_merge_suggestion_history_operated_at', table_name='graph_merge_suggestion_history')
    op.drop_index('idx_merge_suggestion_history_collection_status', table_name='graph_merge_suggestion_history')
    op.drop_index('idx_merge_suggestion_history_collection', table_name='graph_merge_suggestion_history')
    op.drop_table('graph_merge_suggestion_history')
    op.drop_index(op.f('ix_graph_active_merge_suggestions_suggestion_batch_id'), table_name='graph_active_merge_suggestions')
    op.drop_index(op.f('ix_graph_active_merge_suggestions_status'), table_name='graph_active_merge_suggestions')
    op.drop_index(op.f('ix_graph_active_merge_suggestions_collection_id'), table_name='graph_active_merge_suggestions')
    op.drop_index('idx_active_merge_suggestion_created', table_name='graph_active_merge_suggestions')
    op.drop_index('idx_active_merge_suggestion_collection', table_name='graph_active_merge_suggestions')
    op.drop_index('idx_active_merge_suggestion_batch', table_name='graph_active_merge_suggestions')
    op.drop_table('graph_active_merge_suggestions')
    # ### end Alembic commands ###
