"""empty message

Revision ID: 694591d5df94
Revises: add_index_audit_resource
Create Date: 2025-07-11 12:33:38.799759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694591d5df94'
down_revision: Union[str, None] = 'add_index_audit_resource'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_index_merge_suggestions',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=False),
    sa.Column('suggestion_batch_id', sa.String(length=24), nullable=False),
    sa.Column('entity_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('entity_ids_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('merge_reason', sa.Text(), nullable=False),
    sa.Column('suggested_target_entity', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='mergesuggestionstatus'), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'entity_ids_hash', 'gmt_deleted', name='uq_graph_index_merge_suggestion')
    )
    op.create_index('idx_graph_index_merge_suggestion_batch', 'graph_index_merge_suggestions', ['collection_id', 'suggestion_batch_id'], unique=False)
    op.create_index('idx_graph_index_merge_suggestion_collection_status', 'graph_index_merge_suggestions', ['collection_id', 'status'], unique=False)
    op.create_index('idx_graph_index_merge_suggestion_created', 'graph_index_merge_suggestions', ['gmt_created'], unique=False)
    op.create_index('idx_graph_index_merge_suggestion_expires', 'graph_index_merge_suggestions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_graph_index_merge_suggestions_collection_id'), 'graph_index_merge_suggestions', ['collection_id'], unique=False)
    op.create_index(op.f('ix_graph_index_merge_suggestions_gmt_deleted'), 'graph_index_merge_suggestions', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_graph_index_merge_suggestions_status'), 'graph_index_merge_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_graph_index_merge_suggestions_suggestion_batch_id'), 'graph_index_merge_suggestions', ['suggestion_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_index_merge_suggestions_suggestion_batch_id'), table_name='graph_index_merge_suggestions')
    op.drop_index(op.f('ix_graph_index_merge_suggestions_status'), table_name='graph_index_merge_suggestions')
    op.drop_index(op.f('ix_graph_index_merge_suggestions_gmt_deleted'), table_name='graph_index_merge_suggestions')
    op.drop_index(op.f('ix_graph_index_merge_suggestions_collection_id'), table_name='graph_index_merge_suggestions')
    op.drop_index('idx_graph_index_merge_suggestion_expires', table_name='graph_index_merge_suggestions')
    op.drop_index('idx_graph_index_merge_suggestion_created', table_name='graph_index_merge_suggestions')
    op.drop_index('idx_graph_index_merge_suggestion_collection_status', table_name='graph_index_merge_suggestions')
    op.drop_index('idx_graph_index_merge_suggestion_batch', table_name='graph_index_merge_suggestions')
    op.drop_table('graph_index_merge_suggestions')
    # ### end Alembic commands ###
