"""empty message

Revision ID: dcc0b6c56552
Revises: 
Create Date: 2025-06-17 11:34:47.015293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'dcc0b6c56552'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='apikeystatus'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_gmt_deleted'), 'api_key', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_api_key_status'), 'api_key', ['status'], unique=False)
    op.create_index(op.f('ix_api_key_user'), 'api_key', ['user'], unique=False)
    op.create_table('bot',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('type', sa.Enum('knowledge', 'common', name='bottype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='botstatus'), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_gmt_deleted'), 'bot', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_bot_status'), 'bot', ['status'], unique=False)
    op.create_index(op.f('ix_bot_user'), 'bot', ['user'], unique=False)
    op.create_table('bot_collection_relation',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('bot_id', sa.String(length=24), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'collection_id', 'gmt_deleted', name='uq_bot_collection_deleted')
    )
    op.create_table('chat',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('peer_type', sa.Enum('system', 'feishu', 'weixin', 'weixin_official', 'web', 'dingtalk', name='chatpeertype'), nullable=False),
    sa.Column('peer_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='chatstatus'), nullable=False),
    sa.Column('bot_id', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'peer_type', 'peer_id', 'gmt_deleted', name='uq_chat_bot_peer_deleted')
    )
    op.create_index(op.f('ix_chat_bot_id'), 'chat', ['bot_id'], unique=False)
    op.create_index(op.f('ix_chat_gmt_deleted'), 'chat', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_chat_status'), 'chat', ['status'], unique=False)
    op.create_index(op.f('ix_chat_user'), 'chat', ['user'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('INACTIVE', 'ACTIVE', 'DELETED', name='collectionstatus'), nullable=False),
    sa.Column('type', sa.Enum('document', name='collectiontype'), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_gmt_deleted'), 'collection', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_collection_status'), 'collection', ['status'], unique=False)
    op.create_index(op.f('ix_collection_user'), 'collection', ['user'], unique=False)
    op.create_table('config',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('document',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', 'DELETED', name='documentstatus'), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('object_path', sa.Text(), nullable=True),
    sa.Column('doc_metadata', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'name', 'gmt_deleted', name='uq_document_collection_name_deleted')
    )
    op.create_index(op.f('ix_document_collection_id'), 'document', ['collection_id'], unique=False)
    op.create_index(op.f('ix_document_gmt_deleted'), 'document', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_index(op.f('ix_document_user'), 'document', ['user'], unique=False)
    op.create_table('document_indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=24), nullable=False),
    sa.Column('index_type', sa.Enum('vector', 'fulltext', 'graph', name='documentindextype'), nullable=False),
    sa.Column('desired_state', sa.Enum('present', 'absent', name='indexdesiredstate'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('actual_state', sa.Enum('absent', 'creating', 'present', 'deleting', 'failed', name='indexactualstate'), nullable=False),
    sa.Column('observed_version', sa.Integer(), nullable=False),
    sa.Column('index_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_last_reconciled', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'index_type', name='uq_document_index')
    )
    op.create_index(op.f('ix_document_indexes_actual_state'), 'document_indexes', ['actual_state'], unique=False)
    op.create_index(op.f('ix_document_indexes_desired_state'), 'document_indexes', ['desired_state'], unique=False)
    op.create_index(op.f('ix_document_indexes_document_id'), 'document_indexes', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_indexes_id'), 'document_indexes', ['id'], unique=False)
    op.create_index(op.f('ix_document_indexes_index_type'), 'document_indexes', ['index_type'], unique=False)
    op.create_table('invitation',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('admin', 'rw', 'ro', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('lightrag_doc_chunks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('workspace', sa.String(length=255), nullable=False),
    sa.Column('full_doc_id', sa.String(length=256), nullable=True),
    sa.Column('chunk_order_index', sa.Integer(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_vector', Vector(), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'workspace')
    )
    op.create_table('lightrag_doc_full',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('workspace', sa.String(length=255), nullable=False),
    sa.Column('doc_name', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'workspace')
    )
    op.create_table('lightrag_doc_status',
    sa.Column('workspace', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_summary', sa.String(length=255), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'processed', 'failed', name='lightragdocstatus'), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workspace', 'id'),
    sa.UniqueConstraint('workspace', 'id', name='uq_lightrag_doc_status_workspace_id')
    )
    op.create_table('lightrag_llm_cache',
    sa.Column('workspace', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=True),
    sa.Column('return_value', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', 'mode')
    )
    op.create_table('lightrag_vdb_entity',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('workspace', sa.String(length=255), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_vector', Vector(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chunk_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'workspace')
    )
    op.create_table('lightrag_vdb_relation',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('workspace', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=256), nullable=True),
    sa.Column('target_id', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_vector', Vector(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chunk_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'workspace')
    )
    op.create_table('llm_provider',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('completion_dialect', sa.String(length=64), nullable=False),
    sa.Column('embedding_dialect', sa.String(length=64), nullable=False),
    sa.Column('rerank_dialect', sa.String(length=64), nullable=False),
    sa.Column('allow_custom_base_url', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_llm_provider_user_id'), 'llm_provider', ['user_id'], unique=False)
    op.create_table('llm_provider_models',
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('api', sa.Enum('completion', 'embedding', 'rerank', name='apitype'), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('custom_llm_provider', sa.String(length=128), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('provider_name', 'api', 'model')
    )
    op.create_table('message_feedback',
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=True),
    sa.Column('chat_id', sa.String(length=24), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('good', 'bad', name='messagefeedbacktype'), nullable=True),
    sa.Column('tag', sa.Enum('Harmful', 'Unsafe', 'Fake', 'Unhelpful', 'Other', name='messagefeedbacktag'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', name='messagefeedbackstatus'), nullable=True),
    sa.Column('original_answer', sa.Text(), nullable=True),
    sa.Column('revised_answer', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', 'message_id'),
    sa.UniqueConstraint('chat_id', 'message_id', 'gmt_deleted', name='uq_feedback_chat_message_deleted')
    )
    op.create_index(op.f('ix_message_feedback_collection_id'), 'message_feedback', ['collection_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_gmt_deleted'), 'message_feedback', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_message_feedback_status'), 'message_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_message_feedback_user'), 'message_feedback', ['user'], unique=False)
    op.create_table('model_service_provider',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='modelserviceproviderstatus'), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'gmt_deleted', name='uq_model_service_provider_name_deleted')
    )
    op.create_index(op.f('ix_model_service_provider_gmt_deleted'), 'model_service_provider', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_model_service_provider_name'), 'model_service_provider', ['name'], unique=False)
    op.create_index(op.f('ix_model_service_provider_status'), 'model_service_provider', ['status'], unique=False)
    op.create_table('searchtesthistory',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('vector_search', sa.JSON(), nullable=True),
    sa.Column('fulltext_search', sa.JSON(), nullable=True),
    sa.Column('graph_search', sa.JSON(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchtesthistory_collection_id'), 'searchtesthistory', ['collection_id'], unique=False)
    op.create_index(op.f('ix_searchtesthistory_gmt_deleted'), 'searchtesthistory', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_searchtesthistory_user'), 'searchtesthistory', ['user'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('role', sa.Enum('admin', 'rw', 'ro', name='role'), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_quota',
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user', 'key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quota')
    op.drop_table('user')
    op.drop_index(op.f('ix_searchtesthistory_user'), table_name='searchtesthistory')
    op.drop_index(op.f('ix_searchtesthistory_gmt_deleted'), table_name='searchtesthistory')
    op.drop_index(op.f('ix_searchtesthistory_collection_id'), table_name='searchtesthistory')
    op.drop_table('searchtesthistory')
    op.drop_index(op.f('ix_model_service_provider_status'), table_name='model_service_provider')
    op.drop_index(op.f('ix_model_service_provider_name'), table_name='model_service_provider')
    op.drop_index(op.f('ix_model_service_provider_gmt_deleted'), table_name='model_service_provider')
    op.drop_table('model_service_provider')
    op.drop_index(op.f('ix_message_feedback_user'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_status'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_gmt_deleted'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_collection_id'), table_name='message_feedback')
    op.drop_table('message_feedback')
    op.drop_table('llm_provider_models')
    op.drop_index(op.f('ix_llm_provider_user_id'), table_name='llm_provider')
    op.drop_table('llm_provider')
    op.drop_table('lightrag_vdb_relation')
    op.drop_table('lightrag_vdb_entity')
    op.drop_table('lightrag_llm_cache')
    op.drop_table('lightrag_doc_status')
    op.drop_table('lightrag_doc_full')
    op.drop_table('lightrag_doc_chunks')
    op.drop_table('invitation')
    op.drop_index(op.f('ix_document_indexes_index_type'), table_name='document_indexes')
    op.drop_index(op.f('ix_document_indexes_id'), table_name='document_indexes')
    op.drop_index(op.f('ix_document_indexes_document_id'), table_name='document_indexes')
    op.drop_index(op.f('ix_document_indexes_desired_state'), table_name='document_indexes')
    op.drop_index(op.f('ix_document_indexes_actual_state'), table_name='document_indexes')
    op.drop_table('document_indexes')
    op.drop_index(op.f('ix_document_user'), table_name='document')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_gmt_deleted'), table_name='document')
    op.drop_index(op.f('ix_document_collection_id'), table_name='document')
    op.drop_table('document')
    op.drop_table('config')
    op.drop_index(op.f('ix_collection_user'), table_name='collection')
    op.drop_index(op.f('ix_collection_status'), table_name='collection')
    op.drop_index(op.f('ix_collection_gmt_deleted'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_chat_user'), table_name='chat')
    op.drop_index(op.f('ix_chat_status'), table_name='chat')
    op.drop_index(op.f('ix_chat_gmt_deleted'), table_name='chat')
    op.drop_index(op.f('ix_chat_bot_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_table('bot_collection_relation')
    op.drop_index(op.f('ix_bot_user'), table_name='bot')
    op.drop_index(op.f('ix_bot_status'), table_name='bot')
    op.drop_index(op.f('ix_bot_gmt_deleted'), table_name='bot')
    op.drop_table('bot')
    op.drop_index(op.f('ix_api_key_user'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_status'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_gmt_deleted'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
