"""empty message

Revision ID: c5cca2fe6e4e
Revises: 694591d5df94
Create Date: 2025-07-17 10:32:29.699766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cca2fe6e4e'
down_revision: Union[str, None] = '694591d5df94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_summary',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'COMPLETE', 'FAILED', name='collectionsummarystatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('observed_version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_last_reconciled', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', name='uq_collection_summary')
    )
    op.create_index(op.f('ix_collection_summary_collection_id'), 'collection_summary', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_summary_status'), 'collection_summary', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_summary_status'), table_name='collection_summary')
    op.drop_index(op.f('ix_collection_summary_collection_id'), table_name='collection_summary')
    op.drop_table('collection_summary')
    # ### end Alembic commands ###
