"""empty message

Revision ID: b7679c9f05db
Revises: 8e8b89db412c
Create Date: 2025-07-28 13:16:57.866678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7679c9f05db'
down_revision: Union[str, None] = '8e8b89db412c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searchhistory', sa.Column('summary_search', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchhistory', 'summary_search')
    # ### end Alembic commands ###
