# Generated by Django 4.2.6 on 2023-11-21 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deeprag", "0004_alter_document_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="peer_type",
            field=models.CharField(
                choices=[("system", "System"), ("feishu", "Feishu"), ("web", "Web")],
                default="system",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="BotIntegration",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="int406254935c05efd3",
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=256)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("feishu", "Feishu"),
                            ("web", "Web"),
                        ],
                        max_length=16,
                    ),
                ),
                ("config", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("gmt_created", models.DateTimeField(auto_now_add=True)),
                ("gmt_updated", models.DateTimeField(auto_now=True)),
                ("gmt_deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deeprag.bot"
                    ),
                ),
            ],
        ),
    ]
