# Generated by Django 4.2.6 on 2023-12-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeprag', '0008_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='peer_type',
            field=models.CharField(choices=[('system', 'System'), ('feishu', 'Feishu'), ('weixin', 'Weixin'), ('web', 'Web')], default='system', max_length=16),
        ),
    ]
