# Generated by Django 4.2.6 on 2024-01-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deeprag", "0012_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="status",
            field=models.CharField(
                choices=[
                    ("INACTIVE", "Inactive"),
                    ("ACTIVE", "Active"),
                    ("DELETED", "Deleted"),
                    ("QUESTION_PENDING", "Question Pending"),
                ],
                max_length=16,
            ),
        ),
    ]
