# Generated by Django 4.2.6 on 2023-12-14 09:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('deeprag', '0015_apikeytoken'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO deeprag_apikeytoken (id, key, "user", status, count_times, gmt_updated, gmt_created)
                VALUES ('b69854df3988', '8d85a4d4e390474d1745a65d6f1c166c42ef815c', 'github|1765402', 'ACTIVE', 0, NOW(), NOW());
            """,
            reverse_sql=migrations.RunSQL.noop  # 如果需要回滚，这里应该提供相应的SQL语句
        ),
    ]